/* eslint-disable import/prefer-default-export */

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';
export const USER_CHECK_AUTH = 'USER_CHECK_AUTH';

export const UTIL_LOADER_SHOW = 'UTIL_LOADER_SHOW';
export const UTIL_LOADER_HIDE = 'UTIL_LOADER_HIDE';

